### ISSUE TITLE
Azure Automation 

### ISSUE THREAD

**Issue by arunprasathv** [MarczakIO/azure-enterprise-consumption-api#6]
Hi,

My question is not related to this repository. 

I would like to know how to automate the azure deployment to multiple env Dev/QA/PROD. 

From the Development Environment, we create multiple services like Function App, Logic App, Event Grid in Dev Subscription and I want to deploy the code dev /QA/PROD.  how to do it efficiently as we do for other development with CICD.  New to Azure. Impressed with your videos.  Thought your the right person to ASK.       

Also, Let me know to best reach out to you with questions.

I appreciate your Help!!.

Thanks.

**Comment by MarczakIO** [comment]
This is not related to this repository/solution. This is a CI/CD question on ARM deployment.
